spring:
  datasource:
    username: sa
    url: jdbc:h2:tcp://localhost/~/localdb2
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 1000
        show_sql: true
    open-in-view: false

  data:
    web:
      pageable:
        default-page-size: 10
        max-page-size: 200

  h2:
    console:
      enabled: true



logging:
  level:
    org.hibernate.sql: debug